//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studify.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public Nullable<int> idStudent { get; set; }
        public int idProgress { get; set; }
        public Nullable<int> NeededTasks { get; set; }
        public Nullable<int> ComplitedTasks { get; set; }
        public Nullable<int> TaskProgress { get; set; }
        public string LessonName { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
