//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studify.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class TimeTable : INotifyPropertyChanged
    {
        public int idTimeTable { get; set; }
        public Nullable<int> idGroup { get; set; }
        public Nullable<int> Day { get; set; }
        public string LessonName { get; set; }
        public string Auditorium { get; set; }
        public Nullable<int> LessonNumber { get; set; }
        public string LessonType { get; set; }
        public string Week { get; set; }

        public int? day
        {
            get { return Day; }
            set
            {
                Day = value;
                OnPropertyChanged("day");
            }
        }

        public int? lessonNumber
        {
            get { return LessonNumber; }
            set
            {
                LessonNumber = value;
                OnPropertyChanged("lessonNumber");
            }
        }

        public string lessonName
        {
            get { return LessonName; }
            set
            {
                LessonName = value;
                OnPropertyChanged("lessonName");
            }
        }

        public string auditorium
        {
            get { return Auditorium; }
            set
            {
                Auditorium = value;
                OnPropertyChanged("auditorium");
            }
        }

        public string lessonType
        {
            get { return LessonType; }
            set
            {
                LessonType = value;
                OnPropertyChanged("lessonType");
            }
        }

        public virtual Group Group { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;
        public void OnPropertyChanged([CallerMemberName]string prop = "")
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(prop));
        }
    }
}
