//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudifyReminder.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int idTimeTable { get; set; }
        public Nullable<int> idGroup { get; set; }
        public Nullable<int> Day { get; set; }
        public string LessonName { get; set; }
        public string Auditorium { get; set; }
        public Nullable<int> LessonNumber { get; set; }
        public string LessonType { get; set; }
        public string Week { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
